### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/edam-browser#15]
Hi, Could you allow travis to run Continuous integration on IFB-Elixir projects ? It can be done at https://github.com/settings/connections/applications/f244293c729d5066cf27 (from [there](https://github.com/marketplace/travis-ci))

**Comment by lecorguille** [comment]
Done

**Comment by bryan-brancotte** [comment]
thanks !

**Comment by hmenager** [comment]
thank you @lecorguille ;)
