### ISSUE TITLE
Check-boxes for more flexible rendering of sub-ontologies

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/edam-browser#24]
Currently you can have all or one of the EDAM sub-ontologies rendered via:

![capture](https://user-images.githubusercontent.com/1506863/40416982-9d9a5234-5e76-11e8-933a-daf521c67a28.PNG)

It might be nice instead if one could select any combination, by checkboxes

I could imagine *e.g.* wanting see both Data and Formats at the same time.

**Comment by bryan-brancotte** [comment]
Great idea but for now we rely on a json file produced from the owl file containing all the scope.
Could be done in the futur if we rely on a file produce on the fly when asking for a specifique subset of the ontology

**Comment by joncison** [comment]
Just a footnote : OWL subsets (hence JSONs for subontologies) can fairly easily be generated automatically using existing tooling, if we want to do this in future.
