### ISSUE TITLE
Various suggestions (from https://github.com/edamontology/edamontology/issues/299)

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/edam-browser#29]
There are various suggestions in:
https://github.com/edamontology/edamontology/issues/299

which should be tracked in this repo instead.  No easy way to migrate the issue, so please take a look at the above, and close it (and this) once you're happy.

I think some of the stuff in there has already been done, and the rest can be covered by new issue requests in this repo.

**Comment by bryan-brancotte** [comment]
each request transfered
