### ISSUE TITLE
"Expand all" button

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/edam-browser#30]
i.e. which completely expands EDAM Topic, Operation, Data or Format subontology - so I can see **all** concepts for one-click.  It's a big chore currently.

This would be **hugely** useful when using EDAM browser to refactor EDAM.

**Comment by bryan-brancotte** [comment]
Can be done, but i'm really not sure that the tree visualisation is usable after that.
Can be tested by running javascrit 
```js
browser.interactive_tree().cmd().expandAllDescendantElement("owl:Thing"); // in all branch view
browser.interactive_tree().cmd().expandAllDescendantElement("http://edamontology.org/data_0006"); // in data branch view
```

**Comment by joncison** [comment]
Currently I'm expanding the whole tree manually (which sucks) - my specific use-case is I need to see the whole tree to get a quick impression of very deeply nested concepts (also concepts with multiple parents) - to inform periodic EDAM clean-ups.

So it's definitely still usable (just not for typical expected usage /users).
