### ISSUE TITLE
Issuing DOI with zenodoo

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/edam-browser#34]
Hi,
I need to issue a DOI for the EDAM Browser, I've been recommended to use zenodo. Could you allow it to use hook ? You probably received an email requesting this acces.
Thanks

**Comment by lecorguille** [comment]
Zenodo, isn't just for the data?

**Comment by joncison** [comment]
I think a zenodo doi can be minted for pretty much anything ... including software.

**Comment by lecorguille** [comment]
Oki ... Done

**Comment by vdda** [comment]
Agree with Jon
