### ISSUE TITLE
Update for new bio.tools release (was "Too many bio.tools hits - bug ?")

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/edam-browser#36]
![image](https://user-images.githubusercontent.com/1506863/49761908-318c5180-fcc0-11e8-8e16-5341009d98f1.png)

something weird is happening (6643 is obv. not right)

**Comment by joncison** [comment]
ah .. hold on ... this is happening all over the place.  We just made a new deployment of _bio.tools_ so perhaps explains this?  cc @hmenager

**Comment by hmenager** [comment]
indeed, something is seriously wrong with the bio.tools hits.

**Comment by hmenager** [comment]
So, here's how we retrieve the number of entries for sequence alignment analysis:
https://bio.tools/api/tool/?format=json&function=Sequence%20alignment%20analysis
It returns 6643 entries. is this the way the API should work with the new version, or has it changed in some way?
Cheers,
Hervé

**Comment by joncison** [comment]
Ah!   What that now does is a "fuzzy" search across function, meaning input type(s), input format(s), operation(s), output type(s) and output format(s), note and command - which is cool (but very flexible).

It's documented here:
https://biotools.readthedocs.io/en/latest/api_reference_dev.html#attributes

Hold on, I'll dig out the URL you need ...

**Comment by hmenager** [comment]
Fuzzy search behaviour is exactly what I was suspecting we have here. Hopefully, this one should be easy to fix.

**Comment by joncison** [comment]
I *think* this is it:
https://bio.tools/api/tool/?format=json&operationID=operation_0258

which gives 2276 hits (which could be right)

**Comment by joncison** [comment]
Curiously, the equivalent quoted search (for "Sequence alignment") using the UI gives 2210 hits: 
https://bio.tools/?page=1&q=%22Sequence%20analysis%22&sort=score

hmm

@hansioan let's take a look tomorrow

**Comment by hmenager** [comment]
thanks a lot @joncison. as far as EDAM browser goes, I think we can take it from here.

**Comment by joncison** [comment]
sorry ... I forget to read my own docs, the ID search should have been quoted, thus:
https://bio.tools/api/tool/?format=json&operationID="operation_0258"

which returns 43 hits (more like it)

The equivalent search above (which I gave wrongly above .... jeez):
https://bio.tools/?page=1&q=%22Sequence%20alignment%20analysis%22&sort=score

returns 99 hits - which considering it's a fuzzy search, is about right. 

So I think we're in good shape ... :)

**Comment by joncison** [comment]
PS.  huge credits to @bryan-brancotte for this tool - I use it all the time when doing EDAM development, it provides functionality simply no other browser provides

**Comment by hansioan** [comment]
@joncison @hmenager 
No search (quoted or unquoted) is an exact match search. At least not yet. I would suggest either using quoted search or searching by the uri.

**Comment by hansioan** [comment]
The issue is that the entire search needs to be reworked. We either have issues being too strict or too loose in the search results.  I believe that this should be one of our biggest priorities going forward.

**Comment by hansioan** [comment]
In the case of edam-browser, if you want to search by the concepts I would say search by quoted version of the uris (or ids) as they are described here:
https://biotools.readthedocs.io/en/latest/api_reference_dev.html#attributes

For `Sequence alignment analysis` exact match (over the API for now, will soon get it to html side) do:
https://bio.tools/api/t?operationID=%22operation_0258%22

**Comment by joncison** [comment]
There's no way to do it in the UI currently ... which is a nit remis!  @hansioan we need to add "Operation" to the search box facet categories - which I think would then work ?

**Comment by hansioan** [comment]
I will try to fix all of it this week. Will keep you posted.

**Comment by hmenager** [comment]
thanks @hansioan

**Comment by bryan-brancotte** [comment]
@joncison api url links have been updated, the amount of hits is now correct.
@hansioan for now the links I propose to browse to bio.tools are likes https://bio.tools/?operation=%22Sequence%20alignment%20analysis%22 but as soon as we can specify the ID such as something like https://bio.tools/?operationID=%22operation_0258%22 works it will be straight forward to change for us.

**Comment by joncison** [comment]
thanks !  this is on the way, see https://github.com/bio-tools/biotoolsRegistry/issues/385

**Comment by hansioan** [comment]
@hmenager 
I fixed this on the dev server, when you have time could you please take a look so I can push it to production.

//operationID
https://dev.bio.tools/?operationID=%22operation_0258%22

//topicID
https://dev.bio.tools/?topicID=%22topic_3321%22


// dataTypeID works for both input and output data types
https://dev.bio.tools/?dataTypeID=%22data_3154%22

// dataFormatID works for both input and output data formats
https://dev.bio.tools/?dataFormatID=%22format_1921%22

**Comment by hmenager** [comment]
it seems to work @hansioan . The only weird thing is that the filter displays as ":[topic ID] in the search bar:
![image](https://user-images.githubusercontent.com/1140736/49798807-81f8c300-fd43-11e8-870e-bc1d4e7bd0f4.png)

**Comment by hansioan** [comment]
@hmenager 
Yeah I know, but it will have to do for now as that is part of a bigger thing which we will probably have to deal with next year.
But if this is fine, I will push this to production and get back to you

**Comment by hmenager** [comment]
yes, let's do this then! thanks a lot @hansioan for fixing this so quickly. Can you let us know (me and @bryan-brancotte) as soon as you push to production?

**Comment by hansioan** [comment]
@hmenager
Done on the production server, example links below

//operationID
https://bio.tools/?operationID=%22operation_0258%22

//topicID
https://bio.tools/?topicID=%22topic_3321%22

// dataTypeID works for both input and output data types
https://bio.tools/?dataTypeID=%22data_3154%22

// dataFormatID works for both input and output data formats
https://bio.tools/?dataFormatID=%22format_1921%22

**Comment by hansioan** [comment]
@bryan-brancotte 
it should be working, try refreshing your cache

**Comment by joncison** [comment]
yup good for me :)
