### ISSUE TITLE
Missing information in box "Details of term:"

### ISSUE THREAD

**Issue by veitveit** [IFB-ElixirFr/edam-browser#37]
Maybe this is an issue just for formats. 

For instance, take 
http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fformat_3727

EDAMBrowser does not show most of the information.

**Comment by bryan-brancotte** [comment]
Yes indeed many informations were missing, Fixed !

Details : we forgot using --extended when using [edam2json](https://github.com/edamontology/edam2json) and the comment field [was not exported](https://github.com/edamontology/edam2json/pull/5)

**Comment by joncison** [comment]
Thanks for the super-fast action Bryan!

**Comment by bryan-brancotte** [comment]
You are welcome
