### ISSUE TITLE
EDAM 1.25 is out  ... please update EDAM Browser

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/edam-browser#39]
Hi Bryan

Just letting you know that EDAM 1.25 is out ... pls. update EDAM Browser.

Thanks!

cc @hmenager

**Comment by bryan-brancotte** [comment]
Hi @joncison 

It has been done !

Cheers,

**Comment by joncison** [comment]
wow ... thanks for super-fast action :)

**Comment by bryan-brancotte** [comment]
Thanks :)
I should learn about GitHub Action to be even faster !
