### ISSUE TITLE
Links to bio.tools do not resolve

### ISSUE THREAD

**Issue by alaninmcr** [IFB-ElixirFr/edam-browser#42]
The links in the browser to bio.tools do not work (for me)

**Comment by matuskalas** [comment]
Indeed.

@hansioan would you please look at that? Did anything change in the bio.tools interface? _E.g._ https://bio.tools/?inputDataFormatID=%22format_2572%22 doesn't show anything else than the frontpage (while the URL isn't rewritten, which is also is weird).

**Comment by hmenager** [comment]
This needs confirmation from @hansioan but the API has changed, the URL should be:
`https://bio.tools/t?inputID=%27format_2200%27`
(this is from the bio.tools docs here https://biotools.readthedocs.io/en/latest/api_reference.html#attributes)
Once confirmed, I guess the best solution is to change the API call.

**Comment by alaninmcr** [comment]
Thanks I confirm it is now working

**Comment by hansioan** [comment]
the `/t`was missing 

so

`https://bio.tools/t?inputDataFormatID=%22format_2572%22`
is correct
