### ISSUE TITLE
Show relations between branches

### ISSUE THREAD

**Issue by bryan-brancotte** [IFB-ElixirFr/edam-browser#5]
![relation](http://edamontology.org/EDAMrelations.png)

**Comment by bryan-brancotte** [comment]
For curation, we should not only display the format of a data, but also the child format of this data (but maybe a part of it of there is too much data)

**Comment by bryan-brancotte** [comment]
waiting for https://github.com/edamontology/edam2json/issues/2

**Comment by hmenager** [comment]
done, example files here:

[edam2json_with_new_properties.tar.gz](https://github.com/IFB-ElixirFr/edam-browser/files/1687344/edam2json_with_new_properties.tar.gz)

**Comment by bryan-brancotte** [comment]
Fait, par contre je ne met que l'id, n'ayant pas en mémoire les info des autres branches.

[Exemple](https://ifb-elixirfr.github.io/edam-browser/#http://edamontology.org/operation_2409)

**Comment by bryan-brancotte** [comment]
Now we use the text, not the ID. All done=> closing
