### ISSUE TITLE
Commentaires sur le papier en préparation

### ISSUE THREAD

**Issue by cblanchet** [IFB-ElixirFr/edam-browser#8]
Propositions:
- [ ] ajouter une colonne pour EDAMbrowser dans le tableau de comparaison des fonctionnalités
- [x]  fournir un lien vers une ontologie 'custom' pour le critère 6
- [x]  le terme "getter" n'est pas clair

**Comment by bryan-brancotte** [comment]
Lien vers l'ontologie mit, mais aussi le lien [one click open](https://ifb-elixirfr.github.io/edam-browser/?url=https%3A%2F%2Fraw.githubusercontent.com%2FIFB-ElixirFr%2Fedam-browser%2Fmaster%2Fmedia%2Fregular.example.json&identifier_accessor=d.id&text_accessor=d.text#p9&custom_url)

**Comment by bryan-brancotte** [comment]
Pour l'ajout de la colonne, j'ai préféré indiqué dans l'intro du Related work que les critères était recherché par les utilisateurs et auteurs d'EDAM.
