### ISSUE TITLE
EDAM démo : fournir un lien pour un exemple de 'custom ontology'

### ISSUE THREAD

**Issue by cblanchet** [IFB-ElixirFr/edam-browser#9]

**Comment by bryan-brancotte** [comment]
Example file [here](https://github.com/IFB-ElixirFr/edam-browser/blob/master/media/regular.example.json)

Onclick loading [here](https://ifb-elixirfr.github.io/edam-browser/?url=media%2Fregular.example.json&identifier_accessor=d.id&text_accessor=d.text#p9&custom_url)
